import Head from "next/head";
import MoviesSection from "@/components/section/MoviesSection";

export async function getStaticProps() {
  const apiKey = process.env.APIKEY;
  const baseUrl = process.env.BASEURL;
  const res = await fetch(
    `${baseUrl}/movie/upcoming?api_key=${apiKey}&language=en-US&page=1`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home(data) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MoviesSection data={data} header={"Latest Movies"} />
    </>
  );
}
